# Regenerate docs/data_dictionary.md from column_dictionary() + the actual source
# headers in the data. Run from the project root:
#   Rscript --no-save --no-restore scripts/build_data_dictionary.R
#
# The English names/descriptions come from R/column_dictionary.R; the original
# Hindi column headers are read straight from the works table so they are always
# exact. Assumes the targets pipeline has been built (tar_make()).

suppressPackageStartupMessages(library(targets))
source("R/column_dictionary.R")

works_long <- tar_read(works_long)   # Hindi column names, in source order
dict <- column_dictionary()
dict <- dict[order(dict$order), ]

stopifnot(ncol(works_long) == nrow(dict))
source_header <- names(works_long)

esc <- function(x) gsub("|", "\\|", x, fixed = TRUE)

lines <- c(
  "# Data Dictionary — MLA LADS UP Works (FY 2023-24)",
  "",
  "Column reference for the cleaned per-work table produced by the `works_clean`",
  "target (`R/get_works_clean.R`). Each row maps the clean **English name** used",
  "in the cleaned CSV to its **description** and the **original source header**",
  "(Hindi for the portal's own fields; the pipeline adds `district_id`,",
  "`district_name`, `financial_year`, and `status_bucket`).",
  "",
  "> Generated by `scripts/build_data_dictionary.R` — do not edit by hand;",
  "> edit `R/column_dictionary.R` and re-run the script.",
  "",
  "| # | English column | Description | Original source header |",
  "|---|---|---|---|",
  sprintf(
    "| %d | `%s` | %s | %s |",
    dict$order, dict$english, esc(dict$description), esc(source_header)
  ),
  "",
  "## Derived columns — legislator / constituency",
  "",
  "Added by `R/get_works_by_mla.R` (parse) and `R/get_works_mla.R` (canonicalise),",
  "which turn `proposer_name_designation_area` into structured fields. See those",
  "functions for the exact rules.",
  "",
  "| English column | Source target | Description |",
  "|---|---|---|",
  "| `proposer_person` | works_by_mla | Legislator's name, parsed from the text before the \"माननीय विधायक\" marker. NA when the source lists no name. |",
  "| `proposer_role` | works_by_mla | `MLA` (Vidhan Sabha member) or `MLC` (Vidhan Parishad member), from the trailing house tag. |",
  "| `house` | works_by_mla | `Vidhan Sabha` (Legislative Assembly) or `Vidhan Parishad` (Legislative Council). |",
  "| `constituency` | works_by_mla | Constituency / council-seat name, with the `विo सo` (Vidhan Sabha) prefix stripped. |",
  "| `constituency_key` | works_by_mla | Whitespace-stripped join key so spacing variants of a constituency collapse together. |",
  "| `constituency_key_canonical` | works_mla | `constituency_key` after applying human-verified merges from `R/constituency_overrides.R` (identical to it when no override applies). |",
  "| `constituency_canonical` | works_mla | Canonical spelling of the constituency, from the `constituency_crosswalk` target. Use this for grouping/joining. |",
  "",
  "### `constituency_crosswalk` (reference / review artifact)",
  "",
  "One row per seat (`data/processed/constituency_crosswalk.csv`): `proposer_role`,",
  "`house`, `constituency`, `constituency_key`, `n_works`, `n_districts`, `districts`,",
  "`example_proposer`, `n_variant_spellings`, and `near_duplicates`. Fuzzy matching",
  "only **flags** `near_duplicates` for human review — it never merges, because",
  "distinct UP seats often differ by 1-2 characters (e.g. इटवा vs इटावा). Confirmed",
  "same-seat merges go in `R/constituency_overrides.R`.",
  ""
)

con <- file("docs/data_dictionary.md", open = "wb")
writeLines(enc2utf8(lines), con, useBytes = TRUE)
close(con)

cat("Wrote docs/data_dictionary.md with", nrow(dict), "columns.\n")
