# Regenerate data_dictionary.md from column_dictionary() + the actual source
# headers in the data. Run from the project root:
#   Rscript --no-save --no-restore scripts/build_data_dictionary.R
#
# The English names/descriptions come from R/column_dictionary.R; the original
# Hindi column headers are read straight from the works table so they are always
# exact. Assumes the targets pipeline has been built (tar_make()).

suppressPackageStartupMessages(library(targets))
source("R/column_dictionary.R")

works_long <- tar_read(works_long)   # Hindi column names, in source order
dict <- column_dictionary()
dict <- dict[order(dict$order), ]

stopifnot(ncol(works_long) == nrow(dict))
source_header <- names(works_long)

esc <- function(x) gsub("|", "\\|", x, fixed = TRUE)

lines <- c(
  "# Data Dictionary — MLA LADS UP Works (FY 2023-24)",
  "",
  "Column reference for the cleaned per-work table produced by the `works_clean`",
  "target (`R/get_works_clean.R`). Each row maps the clean **English name** used",
  "in the cleaned CSV to its **description** and the **original source header**",
  "(Hindi for the portal's own fields; the pipeline adds `district_id`,",
  "`district_name`, `financial_year`, and `status_bucket`).",
  "",
  "> Generated by `scripts/build_data_dictionary.R` — do not edit by hand;",
  "> edit `R/column_dictionary.R` and re-run the script.",
  "",
  "| # | English column | Description | Original source header |",
  "|---|---|---|---|",
  sprintf(
    "| %d | `%s` | %s | %s |",
    dict$order, dict$english, esc(dict$description), esc(source_header)
  ),
  ""
)

con <- file("data_dictionary.md", open = "wb")
writeLines(enc2utf8(lines), con, useBytes = TRUE)
close(con)

cat("Wrote data_dictionary.md with", nrow(dict), "columns.\n")
